# Latest Docker Compose version
version: "2.3"

# List of Docker container services to run (in this case only one)
services:
  
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml



  # Name of the service ("serve") that serves HTML site
  InputData:

    environment:
       CSVSERVER_BORDER: "orange"
    image: infracloudio/csvserver:latest
    container_name: InputData
    ports:
      - "9393:9300"
    volumes:
      - ${PWD}/inputdata:/csvserver/inputdata
  

    