global:
  scrape_interval: 30s
  scrape_timeout: 10s



scrape_configs:
  - job_name: 'InputData'
    static_configs:
      - targets: ['host.docker.internal:9393']
        labels:
          alias: "InputData"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']